spring:
  application:
    name: PaymentService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9006}
server:
  port: ${SERVER_PORT:8106}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
