spring:
  application:
    name: AdService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9001}
server:
  port: ${SERVER_PORT:8101}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"