spring:
  application:
    name: ProductCatalogService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9007}
server:
  port: ${SERVER_PORT:8107}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"