global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus2
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'spring_micrometer'
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: ['ad-service:8080','cart-service:8080','checkout-service:8080','currency-service:8080',
    'email-service:8080','payment-service:8080','product-catalog-service:8080','recommendation-service:8080','shipping-service:8080']