spring:
  application:
    name: CurrencyService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9004}
server:
  port: ${SERVER_PORT:8104}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"