
spring:
  application:
    name: CartService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9002}
server:
  port: ${SERVER_PORT:8102}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"