spring:
  application:
    name: RecommendationService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9001}
  client:
    product-catalog:
      address: static://${PRODUCT_CATALOG_GRPC_ADDRESS:localhost}:${PRODUCT_CATALOG_GRPC_ADDRESS_PORT:9000}
      negotiationType: PLAINTEXT
server:
  port: ${SERVER_PORT:8082}