spring:
  application:
    name: RecommendationService
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9008}
  client:
    product-catalog:
      address: static://${PRODUCT_CATALOG_GRPC_ADDRESS:localhost}:${PRODUCT_CATALOG_GRPC_ADDRESS_PORT:9007}
      negotiationType: PLAINTEXT
server:
  port: ${SERVER_PORT:8108}
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"